version: '2'
services:
  run:
    build:
      context: .
      dockerfile: Dockerfile
      #command: "bash -c 'which python'"

    command: "bash -c 'cd /covid && python3 main.py /covid/covid_africa.csv'"
  test:
    build:
      context: .
      dockerfile: Dockerfile
      #command: "bash -c 'which python3'"

    command: "bash -c 'cd /covid && python3 test.py'"
